config/routes.rb
Rails.application.routes.draw do
  resources :csv_operators
  resources :csv_attribute_filters
  resources :projects do
    resources :csv_types do
      resources :csv_attributes do
        resources :csv_filters
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/csv_filter.rb
class CsvFilter < ApplicationRecord
  belongs_to :csv_attribute
  belongs_to :csv_operator
end

app/controllers/csv_filters_controller.rb
class CsvFiltersController < ApplicationController
  before_action :set_csv_filter, only: [:show, :edit, :update, :destroy]

  # GET /csv_filters
  # GET /csv_filters.json
  def index
    @csv_filters = CsvFilter.all
  end

  # GET /csv_filters/1
  # GET /csv_filters/1.json
  def show
  end

  # GET /csv_filters/new
  def new
    @project = Project.find params[:project_id]
    @csv_type = @project.csv_types.find params[:csv_type_id]
    @csv_attribute = @csv_type.csv_attributes.find params[:csv_attribute_id]
    @csv_filter = @csv_attribute.csv_filters.new()
  end

  # GET /csv_filters/1/edit
  def edit
  end

  # POST /csv_filters
  # POST /csv_filters.json
  def create
    @csv_filter = CsvFilter.new(csv_filter_params)
    binding.pry
    respond_to do |format|
      if @csv_filter.save
        format.html { redirect_to project_csv_type_csv_attribute_csv_filters_path(@csv_filter.csv_attribute.csv_type.project, @csv_filter.csv_attribute.csv_type, @csv_filter.csv_attribute), notice: 'Csv type was successfully created.' }
        format.json { render :show, status: :created, location: @csv_filter }
      else
        format.html { render :new }
        format.json { render json: @csv_filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /csv_filters/1
  # PATCH/PUT /csv_filters/1.json
  def update
    respond_to do |format|
      if @csv_filter.update(csv_filter_params)
        format.html { redirect_to @csv_filter, notice: 'Csv filter was successfully updated.' }
        format.json { render :show, status: :ok, location: @csv_filter }
      else
        format.html { render :edit }
        format.json { render json: @csv_filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /csv_filters/1
  # DELETE /csv_filters/1.json
  def destroy
    @csv_filter.destroy
    respond_to do |format|
      format.html { redirect_to project_csv_type_csv_attribute_url, notice: 'Csv filter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_csv_filter
      @csv_filter = CsvFilter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def csv_filter_params
      params.require(:csv_filter).permit(:name, :csv_attribute_id, :before_value, :after_value, :compare_value, :csv_operator_id)
    end
end

app/helpers/csv_filters_helper.rb
module CsvFiltersHelper
end

app/views/csv_filters/_form.html.erb
<%= form_for [@project, @csv_type, @csv_attribute, csv_filter], local: true do |form| %>
  <% if csv_filter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(csv_filter.errors.count, "error") %> prohibited this csv_filter from being saved:</h2>

      <ul>
      <% csv_filter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :csv_operator_id %>
    <%= form.select(:csv_operator_id, CsvOperator.all.collect {|u| [u.name, u.id]}) %>
  </div>

  <div class="field">
    <%= form.label :compare_value %>
    <%= form.text_field :compare_value %>
  </div>

  <div class="field">
    <%= form.label :after_value %>
    <%= form.text_field :after_value %>
  </div>

  <div class="field">
    <%= form.label :csv_attribute_id %>
    <%= form.hidden_field :csv_attribute_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/csv_filters/edit.html.erb
<h1>Editing Csv Filter</h1>

<%= render 'form', csv_filter: @csv_filter %>

app/views/csv_filters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Csv Filters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>ValueBefore</th>
      <th>CompareOpeartor</th>
      <th>CompareValue</th>
      <th>ValueAfter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @csv_filters.each do |csv_filter| %>
      <tr>
        <td><%= csv_filter.name %></td>
        <td><%= csv_filter.before_value %></td>
        <td><%= csv_filter.csv_operator&.name %></td>
        <td><%= csv_filter.compare_value %></td>
        <td><%= csv_filter.after_value %></td>
        <td><%= link_to 'Show', project_csv_type_csv_attribute_csv_filters_path %></td>
        <td><%= link_to 'Edit', edit_project_csv_type_csv_attribute_path(csv_filter.csv_attribute.csv_type.project, csv_filter.csv_attribute.csv_type, csv_filter.csv_attribute, csv_filter) %></td>
        <td><%= link_to 'Destroy', project_csv_type_csv_attribute_path(csv_filter.csv_attribute.csv_type.project, csv_filter.csv_attribute.csv_type, csv_filter.csv_attribute, csv_filter), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Csv Filter', new_project_csv_type_csv_attribute_csv_filter_path %>

app/views/csv_filters/new.html.erb
<h1>New Csv Filter</h1>

<%= render 'form', csv_filter: @csv_filter %>

app/views/csv_filters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @csv_filter.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @csv_filter.type %>
</p>

<%= link_to 'Edit', edit_project_csv_type_csv_attribute_csv_filter_path(@csv_filter) %> |