config/routes.rb
Rails.application.routes.draw do
  resources :csv_operators
  resources :csv_attribute_filters
  resources :projects do
    resources :csv_types do
      resources :csv_attributes do
        resources :csv_filters
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/csv_attribute.rb
class CsvAttribute < ApplicationRecord
  belongs_to :csv_type
  has_many :csv_filters
end

app/controllers/csv_attributes_controller.rb
class CsvAttributesController < ApplicationController
  before_action :set_csv_attribute, only: [:show, :edit, :update, :destroy]

  # GET /csv_attributes
  # GET /csv_attributes.json
  def index
    @csv_attributes = CsvAttribute.all
  end

  # GET /csv_attributes/1
  # GET /csv_attributes/1.json
  def show
  end

  # GET /csv_attributes/new
  def new
    @project = Project.find params[:project_id]
    @csv_type = CsvType.find params[:csv_type_id]
    @csv_attribute = CsvAttribute.new(csv_type: @csv_type)
  end

  # GET /csv_attributes/1/edit
  def edit
  end

  # POST /csv_attributes
  # POST /csv_attributes.json
  def create
    @csv_attribute = CsvAttribute.new(csv_attribute_params)

    respond_to do |format|
      if @csv_attribute.save
        format.html { redirect_to project_csv_type_csv_attributes_path(@csv_attribute.csv_type.project, @csv_attribute.csv_type), notice: 'Csv type was successfully created.' }

        format.json { render :show, status: :created, location: @csv_attribute }
      else
        format.html { render :new }
        format.json { render json: @csv_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /csv_attributes/1
  # PATCH/PUT /csv_attributes/1.json
  def update
    respond_to do |format|
      if @csv_attribute.update(csv_attribute_params)
        format.html { redirect_to @csv_attribute, notice: 'Csv attribute was successfully updated.' }
        format.json { render :show, status: :ok, location: @csv_attribute }
      else
        format.html { render :edit }
        format.json { render json: @csv_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /csv_attributes/1
  # DELETE /csv_attributes/1.json
  def destroy
    @csv_attribute.destroy
    respond_to do |format|
      format.html { redirect_to project_csv_type_csv_attributes_url, notice: 'Csv attribute was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_csv_attribute
      @csv_attribute = CsvAttribute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def csv_attribute_params
      params.require(:csv_attribute).permit(:name, :csv_type_id)
    end
end

app/helpers/csv_attributes_helper.rb
module CsvAttributesHelper
end

app/views/csv_attributes/_form.html.erb
<%= form_for [@project, @csv_type, csv_attribute], local: true do |form| %>
  <% if csv_attribute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(csv_attribute.errors.count, "error") %> prohibited this csv_attribute from being saved:</h2>

      <ul>
      <% csv_attribute.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :csv_type_id %>
    <%= form.text_field :csv_type_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/csv_attributes/edit.html.erb
<h1>Editing Csv Attribute</h1>

<%= render 'form', csv_attribute: @csv_attribute %>

<%= link_to 'Show', @csv_attribute %> |
<%= link_to 'Back', csv_attributes_path %>

app/views/csv_attributes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Csv Attributes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Csv type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @csv_attributes.each do |csv_attribute| %>
      <tr>
        <td><%= csv_attribute.name %></td>
        <td><%= csv_attribute.csv_type_id %></td>
        <td><%= link_to 'Show', project_csv_type_csv_attributes_path %></td>
        <td><%= link_to 'Edit', edit_project_csv_type_csv_attribute_path(csv_attribute.csv_type.project, csv_attribute.csv_type, csv_attribute) %></td>
        <td><%= link_to 'Destroy', project_csv_type_csv_attribute_path(csv_attribute.csv_type.project, csv_attribute.csv_type, csv_attribute), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Filters' ,project_csv_type_csv_attribute_csv_filters_path(csv_attribute.csv_type.project, csv_attribute.csv_type, csv_attribute) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Csv Attribute', new_project_csv_type_csv_attribute_path %>

app/views/csv_attributes/new.html.erb
<h1>New Csv Attribute</h1>

<%= render 'form', csv_attribute: @csv_attribute %>

<%= link_to 'Back', project_csv_type_csv_attributes_path %>

app/views/csv_attributes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @csv_attribute.name %>
</p>

<p>
  <strong>Csv type:</strong>
  <%= @csv_attribute.csv_type_id %>
</p>

<%= link_to 'Edit', edit_csv_attribute_path(@csv_attribute) %> |
<%= link_to 'Back', csv_attributes_path %>