config/routes.rb
Rails.application.routes.draw do
  resources :csv_operators
  resources :csv_attribute_filters
  resources :projects do
    resources :csv_types do
      resources :csv_attributes do
        resources :csv_filters
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/csv_types_controller.rb
class CsvTypesController < ApplicationController
  before_action :set_csv_type, only: [:show, :edit, :update, :destroy]

  # GET /csv_types
  # GET /csv_types.json
  def index
    # @csv_types = if params[:project_id].present?
    #   project = Project.find_by(id: params[:project_id])
    #   project.csv_types
    # else
    @csv_types = CsvType.all
  end

  # GET /csv_types/1
  # GET /csv_types/1.json
  def show
  end

  # GET /csv_types/new
  def new
    @project = Project.find params[:project_id]
    @csv_type = CsvType.new(project: @project)
  end

  # GET /csv_types/1/edit
  def edit
  end

  # POST /csv_types
  # POST /csv_types.json
  def create
    @csv_type = CsvType.new(csv_type_params)

    respond_to do |format|
      if @csv_type.save
        format.html { redirect_to project_csv_types_path(@csv_type.project, @csv_type), notice: 'Csv type was successfully created.' }
        format.json { render :show, status: :created, location: @csv_type }
      else
        format.html { render :new }
        format.json { render json: @csv_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /csv_types/1
  # PATCH/PUT /csv_types/1.json
  def update
    respond_to do |format|
      if @csv_type.update(csv_type_params)
        format.html { redirect_to @csv_type, notice: 'Csv type was successfully updated.' }
        format.json { render :show, status: :ok, location: @csv_type }
      else
        format.html { render :edit }
        format.json { render json: @csv_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /csv_types/1
  # DELETE /csv_types/1.json
  def destroy
    @csv_type.destroy
    respond_to do |format|
      format.html { redirect_to csv_types_url, notice: 'Csv type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_csv_type
      @csv_type = CsvType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def csv_type_params
      params.require(:csv_type).permit(:name, :project_id)
    end
end

app/helpers/csv_types_helper.rb
module CsvTypesHelper
end

app/views/csv_types/_form.html.erb
<%= form_for [@project, csv_type], local: true do |form| %>
  <% if csv_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(csv_type.errors.count, "error") %> prohibited this csv_type from being saved:</h2>

      <ul>
      <% csv_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/csv_types/edit.html.erb
<h1>Editing Csv Type</h1>

<%= render 'form', csv_type: @csv_type %>

<%= link_to 'Show', @csv_type %> |
# <%= link_to 'Back', csv_types_path %>

app/views/csv_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Csv Types</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Project</th>
      <th>CsvAttribute</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @csv_types.each do |csv_type| %>
      <tr>
        <td><%= csv_type.id %></td>
        <td><%= csv_type.name %></td>
        <td><%= csv_type.project_id %></td>
        <td><%= link_to 'CsvAttribute', project_csv_type_csv_attributes_path(csv_type.project, csv_type) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Csv Type', new_project_csv_type_path %>

app/views/csv_types/new.html.erb
<h1>New Csv Type</h1>

<%= render 'form', csv_type: @csv_type %>

# <%= link_to 'Back', project_csv_types_path %>

app/views/csv_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @csv_type.name %>
</p>

<p>
  <strong>Project:</strong>
  <%= @csv_type.project_id %>
</p>

<%= link_to 'Edit', edit_csv_type_path(@csv_type) %> |
# <%= link_to 'Back', csv_types_path %>